-- Tabla para cursos libres
CREATE TABLE IF NOT EXISTS cursos_libres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    icono VARCHAR(50) DEFAULT '📚',
    color VARCHAR(100) DEFAULT 'from-blue-500 to-blue-700',
    descripcion TEXT,
    duracion VARCHAR(100),
    modalidad ENUM('presencial', 'virtual', 'hibrido') DEFAULT 'virtual',
    nivel ENUM('basico', 'intermedio', 'avanzado') DEFAULT 'basico',
    instructor VARCHAR(255),
    precio DECIMAL(10,2) DEFAULT 0.00,
    estado ENUM('activo', 'inactivo') DEFAULT 'activo',
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_categoria (categoria),
    INDEX idx_estado (estado),
    INDEX idx_modalidad (modalidad),
    INDEX idx_nivel (nivel)
);

-- Insertar datos de ejemplo basados en el componente CursosLibres.jsx
INSERT INTO cursos_libres (nombre, categoria, icono, color, descripcion, duracion, modalidad, nivel, instructor, precio) VALUES
('Bases de datos y Lenguaje SQL', 'bases-datos', '🗄️', 'from-blue-500 to-blue-700', 'Aprende a gestionar bases de datos con SQL', '2 meses', 'virtual', 'basico', 'Prof. García', 150.00),
('Programación R y RStudio avanzado', 'programacion', '📊', 'from-green-500 to-green-700', 'Análisis estadístico avanzado con R', '3 meses', 'virtual', 'avanzado', 'Prof. López', 200.00),
('Programación Python básico', 'programacion', '🐍', 'from-yellow-500 to-yellow-700', 'Fundamentos de programación en Python', '2 meses', 'virtual', 'basico', 'Prof. Martínez', 180.00),
('Power BI', 'analisis', '📈', 'from-orange-500 to-orange-700', 'Visualización de datos empresariales', '1.5 meses', 'virtual', 'intermedio', 'Prof. Rodríguez', 160.00),
('Servidores en Linux básico', 'sistemas', '🐧', 'from-gray-500 to-gray-700', 'Administración básica de servidores Linux', '2 meses', 'virtual', 'basico', 'Prof. Fernández', 170.00),
('Servidores en Linux avanzado', 'sistemas', '🖥️', 'from-gray-600 to-gray-800', 'Administración avanzada de servidores Linux', '3 meses', 'virtual', 'avanzado', 'Prof. Fernández', 220.00),
('Servidores en Windows básico', 'sistemas', '🪟', 'from-blue-400 to-blue-600', 'Administración básica de servidores Windows', '2 meses', 'virtual', 'basico', 'Prof. Sánchez', 170.00),
('Programación en C#', 'programacion', '⚡', 'from-purple-500 to-purple-700', 'Desarrollo con Microsoft .NET', '3 meses', 'virtual', 'intermedio', 'Prof. Torres', 190.00),
('Programación en C++', 'programacion', '🔧', 'from-blue-500 to-blue-700', 'Programación de sistemas y aplicaciones', '3 meses', 'virtual', 'intermedio', 'Prof. Vega', 190.00),
('Programación en Java', 'programacion', '☕', 'from-red-500 to-orange-500', 'Desarrollo de aplicaciones empresariales', '4 meses', 'virtual', 'intermedio', 'Prof. Morales', 210.00),
('Programación en Python intermedio', 'programacion', '🐍', 'from-green-500 to-blue-500', 'Python para desarrollo web y datos', '2.5 meses', 'virtual', 'intermedio', 'Prof. Martínez', 200.00),
('Programación en Python avanzado', 'programacion', '🚀', 'from-blue-500 to-purple-500', 'Python avanzado y machine learning', '4 meses', 'virtual', 'avanzado', 'Prof. Martínez', 250.00),
('Programación en Laravel', 'programacion', '🌐', 'from-red-500 to-red-700', 'Framework PHP para desarrollo web', '3 meses', 'virtual', 'intermedio', 'Prof. Castro', 200.00),
('Programación Google Colab', 'programacion', '📓', 'from-yellow-500 to-orange-500', 'Notebooks colaborativos en la nube', '1 mes', 'virtual', 'basico', 'Prof. Herrera', 120.00),
('Programación en Go', 'programacion', '🏃', 'from-cyan-500 to-blue-500', 'Lenguaje moderno para sistemas', '2.5 meses', 'virtual', 'intermedio', 'Prof. Ruiz', 190.00),
('Programación Kotlin', 'programacion', '📱', 'from-purple-500 to-pink-500', 'Desarrollo Android moderno', '3 meses', 'virtual', 'intermedio', 'Prof. Jiménez', 200.00),
('Big Data', 'analisis', '📊', 'from-green-600 to-teal-600', 'Análisis de grandes volúmenes de datos', '4 meses', 'virtual', 'avanzado', 'Prof. Mendoza', 280.00),
('Statistica', 'analisis', '📈', 'from-blue-600 to-indigo-600', 'Software estadístico avanzado', '2 meses', 'virtual', 'intermedio', 'Prof. Vargas', 180.00),
('Software Minitab', 'analisis', '📉', 'from-teal-500 to-teal-700', 'Análisis estadístico y control de calidad', '1.5 meses', 'virtual', 'intermedio', 'Prof. Silva', 160.00),
('Software SAS', 'analisis', '📋', 'from-indigo-500 to-indigo-700', 'Análisis estadístico empresarial', '3 meses', 'virtual', 'avanzado', 'Prof. Ramírez', 250.00),
('Software Epidat, Epinfo', 'analisis', '🏥', 'from-green-500 to-green-700', 'Epidemiología y salud pública', '2 meses', 'virtual', 'intermedio', 'Prof. Medina', 170.00),
('Software Stata', 'analisis', '📊', 'from-blue-500 to-blue-700', 'Análisis estadístico y econométrico', '2.5 meses', 'virtual', 'intermedio', 'Prof. Paredes', 190.00),
('Software Eviews', 'analisis', '💹', 'from-purple-500 to-purple-700', 'Análisis econométrico y forecasting', '2.5 meses', 'virtual', 'avanzado', 'Prof. Guerrero', 200.00),
('Cisco Packet Tracert básico', 'redes', '🌐', 'from-blue-600 to-cyan-600', 'Simulación de redes básica', '2 meses', 'virtual', 'basico', 'Prof. Navarro', 170.00),
('Cisco Packet Tracert avanzado', 'redes', '🔗', 'from-cyan-600 to-blue-600', 'Simulación de redes avanzada', '3 meses', 'virtual', 'avanzado', 'Prof. Navarro', 220.00),
('Internet de las cosas', 'tecnologia', '🌍', 'from-green-500 to-teal-500', 'IoT y dispositivos conectados', '3 meses', 'virtual', 'intermedio', 'Prof. Delgado', 210.00),
('Administración de Moodle I', 'sistemas', '🎓', 'from-orange-500 to-orange-700', 'Plataforma educativa básica', '1.5 meses', 'virtual', 'basico', 'Prof. Ortega', 140.00),
('Administración de Moodle II', 'sistemas', '🏫', 'from-orange-600 to-red-600', 'Plataforma educativa avanzada', '2 meses', 'virtual', 'intermedio', 'Prof. Ortega', 170.00),
('Scratch', 'programacion', '🧩', 'from-yellow-500 to-orange-500', 'Programación visual para principiantes', '1 mes', 'virtual', 'basico', 'Prof. Peña', 100.00),
('ArcGIS', 'gis', '🗺️', 'from-green-600 to-blue-600', 'Sistemas de información geográfica', '3 meses', 'virtual', 'intermedio', 'Prof. Campos', 230.00),
('Oracle', 'bases-datos', '🏛️', 'from-red-600 to-red-800', 'Base de datos empresarial', '4 meses', 'virtual', 'avanzado', 'Prof. García', 280.00),
('MariaDB', 'bases-datos', '🐬', 'from-blue-500 to-teal-500', 'Base de datos open source', '2 meses', 'virtual', 'intermedio', 'Prof. García', 160.00),
('MongoDB', 'bases-datos', '🍃', 'from-green-600 to-green-800', 'Base de datos NoSQL', '2.5 meses', 'virtual', 'intermedio', 'Prof. García', 180.00),
('Latex', 'documentos', '📝', 'from-gray-600 to-gray-800', 'Composición tipográfica profesional', '1.5 meses', 'virtual', 'intermedio', 'Prof. Ramos', 140.00),
('Microsoft Excel Avanzado', 'oficina', '📊', 'from-green-500 to-green-700', 'Análisis de datos con Excel', '2 meses', 'virtual', 'intermedio', 'Prof. Moreno', 150.00),
('Microsoft Word Avanzado', 'oficina', '📝', 'from-blue-500 to-blue-700', 'Documentos profesionales', '1 mes', 'virtual', 'basico', 'Prof. Moreno', 120.00),
('Microsoft PowerPoint', 'oficina', '📽️', 'from-orange-500 to-orange-700', 'Presentaciones impactantes', '1 mes', 'virtual', 'basico', 'Prof. Moreno', 120.00),
('Google Workspace', 'oficina', '🌐', 'from-blue-400 to-green-400', 'Productividad en la nube', '1.5 meses', 'virtual', 'basico', 'Prof. Aguilar', 130.00),
('Programación en JavaScript', 'programacion', '⚡', 'from-yellow-400 to-orange-500', 'Desarrollo web interactivo', '3 meses', 'virtual', 'intermedio', 'Prof. Castro', 190.00),
('React.js', 'programacion', '⚛️', 'from-cyan-400 to-blue-500', 'Interfaces de usuario modernas', '3 meses', 'virtual', 'intermedio', 'Prof. Castro', 210.00),
('Node.js', 'programacion', '🟢', 'from-green-400 to-green-600', 'Backend con JavaScript', '2.5 meses', 'virtual', 'intermedio', 'Prof. Castro', 200.00),
('Vue.js', 'programacion', '💚', 'from-green-500 to-teal-500', 'Framework progresivo', '2.5 meses', 'virtual', 'intermedio', 'Prof. Vásquez', 190.00),
('Angular', 'programacion', '🅰️', 'from-red-500 to-red-700', 'Aplicaciones web robustas', '3.5 meses', 'virtual', 'avanzado', 'Prof. Vásquez', 220.00),
('Docker', 'sistemas', '🐳', 'from-blue-400 to-cyan-500', 'Contenedores y virtualización', '2 meses', 'virtual', 'intermedio', 'Prof. Fernández', 180.00),
('Kubernetes', 'sistemas', '☸️', 'from-blue-600 to-purple-600', 'Orquestación de contenedores', '3 meses', 'virtual', 'avanzado', 'Prof. Fernández', 250.00),
('AWS Cloud', 'cloud', '☁️', 'from-orange-400 to-yellow-500', 'Servicios en la nube', '4 meses', 'virtual', 'intermedio', 'Prof. Salazar', 300.00),
('Azure Cloud', 'cloud', '☁️', 'from-blue-500 to-blue-700', 'Plataforma Microsoft Cloud', '4 meses', 'virtual', 'intermedio', 'Prof. Salazar', 300.00),
('Google Cloud', 'cloud', '☁️', 'from-blue-400 to-green-400', 'Infraestructura Google', '4 meses', 'virtual', 'intermedio', 'Prof. Salazar', 300.00),
('Cyberseguridad', 'seguridad', '🔒', 'from-red-600 to-gray-800', 'Protección de sistemas', '4 meses', 'virtual', 'avanzado', 'Prof. Navarro', 280.00)
ON DUPLICATE KEY UPDATE nombre=nombre;